spring:
  application:
    name: clearops
  datasource:
    url: jdbc:mysql://localhost:3306/clearopsdb?useTimezone=true&serverTimezone=UTC
    username: ${usernameDB}
    password: ${passwordDB}
  mvc:
    format:
      currency=pt_BR: